### ISSUE TITLE
To-do Launch

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/rentswatch-app#16]
**Pirhoo**
- [x] Jeudi : Propagation DNS

**Anne-Lise**
- [x] Vérifier le GA
- [x] Relire les textes
- [x] Intégrer la vidéo dans la prez power point
- [x] Vérifier partage réseaux sociaux résultats quiz et app
- [x] Ouvrir la page Facebook

**Nico**
- [x] Traduire les nouveaux textes en allemand (changement des currencies)
